### PR TITLE
Initial version of improved build script

### PR DESCRIPTION
**Pull request by asm0dey**
I've improved buidscript a bit — now it accepts named arguments and may print help if needed (which may be useful). It preserves the same arguments, but doesn't rely on tem being put on concrete positions.

### CODE REVIEW

**Comment by SerVB** [comment]
Thank you for the PR. Actually, all these scripts are just demos of how you can build your container so there has been no intention to make them friendlier to use.

I think your change makes sense but there are some problems:
1. Documentation in README now seems to be outdated.
2. It's convenient for developing to have similar logic in `build-container-dev.sh` too, but you haven't updated it. Since there is much new code, maybe just merge these two scripts?
3. Not tested yet but I think that `set -x # Activate debugging to show execution details: all commands will be printed before execution` might now print too much info. This was used to show users how little commands we required but I believe that new parsing is not something that a user wants to see.
4. I think if someone wants to understand how to build our container, they now have to read more and it can be scary.

So **my final proposal** is to extract a very simple script like previous `build-container.sh`, even without default arguments. And provide a user-friendly script that parses `dev`, `downloadUrl`, and `containerName` and invokes that simple script with proper params.

So in README we could say that simple script is used to build the container, but we have one more script that makes building easier for users who don't want to change our scripts.

What do you think?

**Review by SerVB — CHANGES_REQUESTED** [review]
So I think it can't be accepted in the current state.

**Comment by asm0dey** [comment]
Oh, of course another scripts should be changed this way and README should be changed. This work is not intended to be accepted as is and thank you for comments. I wanted to check if you think it makes sense at all.

I can see next steps as following:

1. Add `.env` file with necessary variables
2. Add script that will call subsequent `clone`, `build` etc scripts reusing environment variables from `.env`
3. Update all scripts to be able to work with `getopts` to make them self-descriptive
4. Remove `set -x`

WDYT?

**Comment by SerVB** [comment]
> next steps

Maybe :) They will make our scripts handier for those who just want to launch our scripts without editing. We should ensure that we leave quite understandable and easy usage for those who want to customize the scripts or don't have Bash. Anyway, thank you for the ideas.

Let me close this PR for now. I've filed a ticket with a link to it: https://youtrack.jetbrains.com/issue/PRJ-215

**Pull request closed without merging**
